name: ci-go-workflow
on: 
    pull_request:
        branches: [develop]
jobs:
    check-application:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Check application
              uses: actions/setup-go@v2
              with:
                  go-version: 1.21
            - name: Check application
              run: |
                  go test
                  go run math.go
