name: ci-go-workflow
on: 
    pull_request:
        branches: [develop]
jobs:
    check-application:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                go-version: ['latest','1.21']
                node-version: ['16']
        steps:
            - name: Check application with Node.js ${{matrix.node-version}}
              uses: actions/checkout@v2
              with:
                node-version: 16
            - name: Check Go ${{matrix.go-version}} application
              uses: actions/setup-go@v2
              with:
                  go-version: ${{ matrix.go-version }}
            - name: Check application
              run: |
                  go test
                  go run math.go
