name: ci-go-workflow
on: 
    pull_request:
        branches: [develop]
jobs:
    check-application:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                go-version: ['1.21','1.20']
                node-version: ['16']
        steps:
            - name: Check application with Node.js ${{matrix.node-version}}
              uses: actions/checkout@v2
              with:
                node-version: 16
            - name: Install and Check Go ${{matrix.go-version}} application
            #   uses: actions/setup-go@v2
            #   with:
            #       go-version: ${{ matrix.go-version }}
            # - name: Check application
              run: |
              
                if [[ "${{ matrix.go-version }}" == "1.20" ]]; then
                    sudo apt-get update
                    sudo apt-get install -y golang-1.20
                fi
              
              
                if [[ "${{ matrix.go-version }}" == "1.21" ]]; then
                    sudo apt-get update
                    sudo apt-get install -y golang-1.21
                fi
                
                
                if [[ "${{ matrix.go-version }}" == "1.20" ]]; then
                    export PATH="/usr/lib/go-1.20/bin:$PATH"
                elif [[ "${{ matrix.go-version }}" == "1.21" ]]; then
                    export PATH="/usr/lib/go-1.21/bin:$PATH"
                fi
                
                go version
                
                go test
                go run math.go
